FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
        iproute2 \
        nftables \
        procps \
        python3 \
        iputils-ping \
        curl \
        tcpdump && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work

CMD python3 main.py -debug \
    -key "$IPUDP_KEY" \
    -client $IPUDP_SERVER_IP:$IPUDP_PORT -tunnel udp
