FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        iproute2 \
        nftables \
        procps \
        python3 \
        iputils-ping \
        curl \
        tcpdump && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work

ENTRYPOINT ["python3", "main.py"]
